[package]
name = "kb-llm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tracing = "0.1"
kb-error = { path = "../kb-error" }

